
'''
Each new term in the Fibonacci sequence is generated by adding the previous two 
terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed 
four million, find the sum of the even-valued terms.

'''
import numpy as np
def Fibonacci(N):
    # N is the cutoff value for the number
    fib = [1, 2]
    while fib[-1] <= N:
        new_term = fib[-1] + fib[-2]
        fib.append(new_term)
    # Find even-valued terms:
    even_fib = []
    for val in fib:
        if val%2==0:
            even_fib.append(val)
    sum_even_fib = np.sum(even_fib)
    
    return sum_even_fib
#%%
Fibonacci(4000000)
    